object Versions {
    const val lifecycle = "2.7.0"
    const val core = "1.12.0"
    const val kotlin = "1.9.22"
    const val compose = "1.6.1"
    const val activityCompose = "1.8.2"
    const val accompanist = "0.28.0"
    const val navigation = "2.7.7"
    const val composeCompiler = "1.5.9"
    const val material3 = "1.2.0"
    const val facebookSdk = "15.0.2"
    const val audienceNetwork = "6.14.0"
    const val firebaseBom = "32.2.7"
    const val hilt = "2.50"
    const val gson = "2.10.1"
    const val retrofit = "2.9.0"
    const val room = "2.6.1"
    const val paging = "3.2.1"
    const val coroutines = "1.7.3"

    const val coil = "2.4.0"
    const val dataStore = "1.0.0"
    const val shimmer = "1.2.0"
}